import type { SpeedChallenge } from './types'

export interface ChallengeCategory {
  id: string
  nameAr: string
  emoji: string
}

export const CHALLENGE_CATEGORIES: ChallengeCategory[] = [
  { id: 'physical', nameAr: 'حركات جسدية', emoji: '🏃' },
  { id: 'vocal',    nameAr: 'أصوات وكلام',  emoji: '🗣️' },
  { id: 'thinking', nameAr: 'تفكير وإجابة', emoji: '🧠' },
  { id: 'creative', nameAr: 'تمثيل وإبداع', emoji: '🎭' },
  { id: 'emoji',    nameAr: 'وجوه وإيموجي',  emoji: '😊' },
]

export const CHALLENGES: SpeedChallenge[] = [
  // ── Physical ──────────────────────────────────────────────────────────────
  { text: 'أسرع واحد يصفق ٥ مرات', categoryId: 'physical' },
  { text: 'أسرع واحد يقف على قدم واحدة لمدة ٣ ثوانٍ', categoryId: 'physical' },
  { text: 'أسرع واحد يلمس أرض الغرفة بكلتا يديه', categoryId: 'physical' },
  { text: 'أسرع واحد يدور دورة كاملة حول نفسه', categoryId: 'physical' },
  { text: 'أسرع واحد يقفز ٣ مرات', categoryId: 'physical' },
  { text: 'أسرع واحد يلمس أصابع قدميه دون أن يثني ركبتيه', categoryId: 'physical' },
  { text: 'أسرع واحد يضع يديه على رأسه', categoryId: 'physical' },
  { text: 'أسرع واحد يمشي ١٠ خطوات للخلف', categoryId: 'physical' },
  { text: 'أسرع واحد يجلس على الأرض ثم يقف مرة أخرى', categoryId: 'physical' },
  { text: 'أسرع واحد يلف لسانه ويُبرزه', categoryId: 'physical' },
  { text: 'أسرع واحد يرمش بعينيه ١٠ مرات', categoryId: 'physical' },
  { text: 'أسرع واحد يضرب يديه على ركبتيه ٥ مرات', categoryId: 'physical' },
  { text: 'أسرع واحد يُقلّد حركة السباحة واقفًا', categoryId: 'physical' },
  { text: 'أسرع واحد يمد يده اليمنى ويلمس أذنه اليسرى', categoryId: 'physical' },
  { text: 'أسرع واحد يقف ويجلس ٣ مرات متتالية', categoryId: 'physical' },
  { text: 'أسرع واحد يُقلّد حركة الدجاج', categoryId: 'physical' },
  { text: 'أسرع واحد يضع يده على قلبه ويُحيّي الآخرين', categoryId: 'physical' },
  { text: 'أسرع واحد يهز كتفيه ٥ مرات', categoryId: 'physical' },
  { text: 'أسرع واحد يُقلّد حركة الوثب فوق حاجز وهمي', categoryId: 'physical' },
  { text: 'أسرع واحد يلوّح بيده للجميع ابتسامةً', categoryId: 'physical' },
  { text: 'أسرع واحد يُقلّد المشية العسكرية ٥ خطوات', categoryId: 'physical' },
  { text: 'أسرع واحد يضحك بصوت عالٍ ثم يتوقف فجأة', categoryId: 'physical' },
  { text: 'أسرع واحد يُقلّد حركة الكاراتيه', categoryId: 'physical' },
  { text: 'أسرع واحد يُقلّد قيادة سيارة', categoryId: 'physical' },
  { text: 'أسرع واحد يلمس حائطين مختلفين في الغرفة', categoryId: 'physical' },
  { text: 'أسرع واحد يُقلّد نومه', categoryId: 'physical' },
  { text: 'أسرع واحد يضع يديه خلف ظهره', categoryId: 'physical' },
  { text: 'أسرع واحد يحرك حاجبيه للأعلى ٣ مرات', categoryId: 'physical' },
  { text: 'أسرع واحد يُقلّد حركة الروبوت في ٥ ثوانٍ', categoryId: 'physical' },
  { text: 'أسرع واحد يُقلّد ملاكمًا يتحرك', categoryId: 'physical' },

  // ── Vocal ─────────────────────────────────────────────────────────────────
  { text: 'أسرع واحد يعدّ من ١ إلى ١٠ بالعربي', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول اسمه بالمقلوب', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت الأذان', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت القطة', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت الكلب', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول ٣ دول عربية', categoryId: 'vocal' },
  { text: 'أسرع واحد يُغنّي مقطعًا من أغنية شعبية', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول ٥ فواكه بسرعة', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت الطائرة', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت الفرامل', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول "بسم الله الرحمن الرحيم" ٣ مرات', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت الحوت', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول ٣ ألوان متتالية بسرعة', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت المذيع الإخباري', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول اسم ٣ لاعبي كرة قدم', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت السيارة عند الإقلاع', categoryId: 'vocal' },
  { text: 'أسرع واحد يُغنّي أول سطر من أغنية أطفال', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول ٥ حيوانات بحرية', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت المطر', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول جملة "الجمل والجمل والجمال" ٣ مرات', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت الغضب دون كلام', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول ٣ أنواع رياضة', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت الطفل يبكي', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول الحروف الهجائية من الألف للياء', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت الريح الشديدة', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول ٣ أطباق سعودية', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت التصفير', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت النحلة', categoryId: 'vocal' },
  { text: 'أسرع واحد يقول ٥ أسماء أشخاص في الغرفة', categoryId: 'vocal' },
  { text: 'أسرع واحد يُقلّد صوت روبوت يتحدث', categoryId: 'vocal' },

  // ── Thinking ──────────────────────────────────────────────────────────────
  { text: 'أسرع واحد يقول عاصمة المملكة العربية السعودية', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ناتج ٧ × ٨', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول اسم نبي من الأنبياء الكرام', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ٣ دول في قارة أفريقيا', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ١٠٠ - ٣٧', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول اسم ٣ ألوان قوس قزح', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول شيئًا يوجد في المطبخ يبدأ بحرف الميم', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ٣ أنواع من الحلويات السعودية', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول عدد أيام السنة', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول اسم ٣ أنهار عالمية', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول كلمة تبدأ بحرف الضاد', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ناتج ١٢ × ١٢', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ٣ دول آسيوية', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول أقرب دولة خليجية للمملكة من الشمال', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول شيئًا أزرق اللون في الغرفة', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ٣ أنواع من الطيور', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ناتج ١٥ + ٢٨', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول عاصمة فرنسا', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول شيئًا يُستخدم في الرياضة', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول شيئًا حارًّا يبدأ بحرف الشين', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ٣ علماء مسلمين', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول عدد لاعبي كرة القدم في الملعب', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول كلمة عربية مضادة لكلمة "بارد"', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ٣ أشياء توجد في الحقيبة المدرسية', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول عاصمة اليابان', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول شيئًا يُشترى من البقالة يبدأ بحرف العين', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ٣ رياضات أولمبية', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول ناتج ٢٥ × ٤', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول أعلى جبل في العالم', categoryId: 'thinking' },
  { text: 'أسرع واحد يقول اسم مدينة سعودية تبدأ بحرف الجيم', categoryId: 'thinking' },

  // ── Creative ──────────────────────────────────────────────────────────────
  { text: 'أسرع واحد يُمثّل شخص يأكل سوشي لأول مرة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل أستاذًا يشرح في الفصل', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يفتح هديةً مفاجئة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا وجد مبلغًا كبيرًا في الشارع', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل رجل الأمن عند البوابة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل طيّارًا يُعلن عن الهبوط', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يحاول إقناع أمّه بشيء', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل بائع فاكهة في السوق', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يرى شبحًا', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل لاعبًا سجّل هدفًا في الدقيقة الأخيرة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا ينتظر في الطابور منذ ساعة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل طبيبًا يفحص مريضًا', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يقود دراجة هوائية في المنحدر', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل مُذيعًا يُقدّم نشرة أخبار عاجلة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا ينظر في المرآة بإعجاب', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل طاهيًا يتذوّق طبقه ويُعلن رأيه', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يسمع خبرًا صادمًا', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يُحاول رفع حقيبة ثقيلة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل مدرّبًا يُحفّز فريقه قبل المباراة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا ينظر إلى شيء بعيد جدًّا', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا في عاصفة ريح شديدة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل ممثلًا يتلقى جائزة أوسكار', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يُحاول تذكّر شيء نسيه', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل سائق تاكسي يتذمّر من الزحمة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يأكل ليمونًا مباشرةً', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يصحو من نوم عميق', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل عارض أزياء على المنصة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يُجري مقابلة عمل', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل لاعب بلياردو يستعدّ للضربة', categoryId: 'creative' },
  { text: 'أسرع واحد يُمثّل شخصًا يطير في الفضاء لأول مرة', categoryId: 'creative' },

  // ── Emoji ─────────────────────────────────────────────────────────────────
  { text: 'أسرع واحد يُعبّر بوجهه عن الدهشة الكاملة', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الضحك الصامت', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الحزن العميق', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الغضب الشديد', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الاشمئزاز', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الخوف من شيء خلفه', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن التعجب والاستغراب', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن التثاؤب الكبير', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الطمأنينة والسعادة', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الإرباك والحيرة', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 🤔 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 😎 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 🥺 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 🤩 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 😂 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 😱 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 🤯 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 😤 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 🥳 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 😴 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الشعور بالبرد الشديد', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الشعور بالحر الشديد', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن وجع الأسنان', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن أكل شيء لذيذ جدًّا', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن رائحة كريهة', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الإعجاب والإطراء', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 🤫 ويُشير للصمت', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن إيموجي 😏 بالكامل', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن رؤية شيء صغير جدًّا', categoryId: 'emoji' },
  { text: 'أسرع واحد يُعبّر بوجهه عن الانتصار والفخر', categoryId: 'emoji' },
]

export function buildChallengePool(selectedCategories: string[]): SpeedChallenge[] {
  return CHALLENGES.filter((c) => selectedCategories.includes(c.categoryId))
}
