import type { SpeedChallenge } from './types'

export interface ChallengeCategory {
  id: string
  nameAr: string
  emoji: string
}

export const CHALLENGE_CATEGORIES: ChallengeCategory[] = [
  { id: 'physical', nameAr: 'حركات', emoji: '🏃' },
  { id: 'vocal',    nameAr: 'أصوات', emoji: '🗣️' },
  { id: 'thinking', nameAr: 'تفكير', emoji: '🧠' },
  { id: 'creative', nameAr: 'تمثيل', emoji: '🎭' },
]

export const CHALLENGES: SpeedChallenge[] = [
  // ── Physical ──────────────────────────────────────────────────────────────
  { text: 'صفّق ٥ مرات', categoryId: 'physical' },
  { text: 'دُر دورة كاملة', categoryId: 'physical' },
  { text: 'قف على قدم واحدة ٣ ثواني', categoryId: 'physical' },
  { text: 'العب ٣ قفزات', categoryId: 'physical' },
  { text: 'العب الروبوت ٥ ثواني', categoryId: 'physical' },
  { text: 'العب الكاراتيه ضربتين', categoryId: 'physical' },
  { text: 'العب قيادة سيارة ٥ ثواني', categoryId: 'physical' },
  { text: 'العب السباحة واقفاً', categoryId: 'physical' },
  { text: 'العب الدجاجة', categoryId: 'physical' },
  { text: 'العب الملاكمة ٥ ثواني', categoryId: 'physical' },
  { text: 'العب المشية العسكرية ٥ خطوات', categoryId: 'physical' },
  { text: 'لمس الأرض بكلتا يديك', categoryId: 'physical' },
  { text: 'لمس أصابع قدميك', categoryId: 'physical' },
  { text: 'لمس حائطين مختلفين', categoryId: 'physical' },
  { text: 'يد يمنى على أذن يسرى', categoryId: 'physical' },
  { text: 'اجلس وقف ٣ مرات', categoryId: 'physical' },
  { text: 'امشِ ١٠ خطوات للخلف', categoryId: 'physical' },
  { text: 'هز كتفيك ٥ مرات', categoryId: 'physical' },
  { text: 'رمش ١٠ مرات بسرعة', categoryId: 'physical' },
  { text: 'اضحك بصوت ثم توقف فجأة', categoryId: 'physical' },
  { text: 'حرك حاجبيك للأعلى ٣ مرات', categoryId: 'physical' },
  { text: 'اضرب ركبتيك ٥ مرات', categoryId: 'physical' },
  { text: 'لوّح للجميع بيدين معاً', categoryId: 'physical' },
  { text: 'يدك خلف ظهرك ٣ ثواني', categoryId: 'physical' },
  { text: 'قف كالتمثال ٥ ثواني بدون حراك', categoryId: 'physical' },
  { text: 'العب النوم ٣ ثواني ثم انهض', categoryId: 'physical' },
  { text: 'قفز فوق حاجز وهمي', categoryId: 'physical' },
  { text: 'اتمدد على الأرض ثم قم', categoryId: 'physical' },
  { text: 'العب وزن ثقيل جداً', categoryId: 'physical' },
  { text: 'تحرك كالروبوت المعطل', categoryId: 'physical' },

  // ── Vocal ─────────────────────────────────────────────────────────────────
  { text: 'صوت القطة', categoryId: 'vocal' },
  { text: 'صوت الكلب', categoryId: 'vocal' },
  { text: 'صوت الطائرة', categoryId: 'vocal' },
  { text: 'صوت الفرامل', categoryId: 'vocal' },
  { text: 'صوت النحلة', categoryId: 'vocal' },
  { text: 'صوت الحوت', categoryId: 'vocal' },
  { text: 'صوت الريح', categoryId: 'vocal' },
  { text: 'صوت المطر', categoryId: 'vocal' },
  { text: 'صوت طفل يبكي', categoryId: 'vocal' },
  { text: 'صوت روبوت يتكلم', categoryId: 'vocal' },
  { text: 'صوت سيارة تشتغل', categoryId: 'vocal' },
  { text: 'صوت مذيع أخبار', categoryId: 'vocal' },
  { text: 'عدّ ١ للـ ١٠', categoryId: 'vocal' },
  { text: '٣ دول عربية', categoryId: 'vocal' },
  { text: '٥ فواكه', categoryId: 'vocal' },
  { text: '٥ حيوانات بحرية', categoryId: 'vocal' },
  { text: '٣ أنواع رياضة', categoryId: 'vocal' },
  { text: '٣ ألوان', categoryId: 'vocal' },
  { text: 'الحروف الهجائية', categoryId: 'vocal' },
  { text: 'اسمك بالمقلوب', categoryId: 'vocal' },
  { text: 'غنّ مقطع أي أغنية', categoryId: 'vocal' },
  { text: 'غنّ أغنية أطفال', categoryId: 'vocal' },
  { text: 'صفّر بفمك', categoryId: 'vocal' },
  { text: '٣ أشخاص في الغرفة دور على اسمهم', categoryId: 'vocal' },
  { text: 'صوت غضب بدون كلام', categoryId: 'vocal' },
  { text: 'قلد صوت مقدم برنامج', categoryId: 'vocal' },
  { text: '٣ أطباق سعودية', categoryId: 'vocal' },
  { text: '٣ مدن سعودية', categoryId: 'vocal' },
  { text: '٣ لاعبي كرة قدم', categoryId: 'vocal' },
  { text: 'قلد ضحكة شخص في الغرفة', categoryId: 'vocal' },

  // ── Thinking ──────────────────────────────────────────────────────────────
  { text: 'مضاد: بارد', categoryId: 'thinking' },
  { text: 'مضاد: صغير', categoryId: 'thinking' },
  { text: 'مضاد: سريع', categoryId: 'thinking' },
  { text: 'مضاد: قريب', categoryId: 'thinking' },
  { text: 'مضاد: ليل', categoryId: 'thinking' },
  { text: 'مضاد: فرح', categoryId: 'thinking' },
  { text: 'مضاد: صعب', categoryId: 'thinking' },
  { text: 'مضاد: ثقيل', categoryId: 'thinking' },
  { text: 'مضاد: فوق', categoryId: 'thinking' },
  { text: 'مضاد: قديم', categoryId: 'thinking' },
  { text: '٧ × ٨', categoryId: 'thinking' },
  { text: '١٢ × ١٢', categoryId: 'thinking' },
  { text: '١٠٠ - ٣٧', categoryId: 'thinking' },
  { text: '١٥ + ٢٨', categoryId: 'thinking' },
  { text: '٢٥ × ٤', categoryId: 'thinking' },
  { text: '٩٠ ÷ ٦', categoryId: 'thinking' },
  { text: 'عاصمة: فرنسا', categoryId: 'thinking' },
  { text: 'عاصمة: اليابان', categoryId: 'thinking' },
  { text: 'عاصمة: المملكة', categoryId: 'thinking' },
  { text: 'عاصمة: مصر', categoryId: 'thinking' },
  { text: 'عاصمة: تركيا', categoryId: 'thinking' },
  { text: 'كلمة تبدأ بـ: ض', categoryId: 'thinking' },
  { text: 'كلمة تبدأ بـ: خ', categoryId: 'thinking' },
  { text: 'كلمة تبدأ بـ: ث', categoryId: 'thinking' },
  { text: 'شيء في المطبخ يبدأ بـ: م', categoryId: 'thinking' },
  { text: 'شيء أزرق في الغرفة', categoryId: 'thinking' },
  { text: 'كم لاعب في فريق كرة القدم؟', categoryId: 'thinking' },
  { text: 'كم يوم في السنة؟', categoryId: 'thinking' },
  { text: 'أعلى جبل في العالم', categoryId: 'thinking' },
  { text: 'اسم نبي يبدأ بـ: م', categoryId: 'thinking' },

  // ── Creative ──────────────────────────────────────────────────────────────
  { text: 'مثّل: تأكل سوشي لأول مرة', categoryId: 'creative' },
  { text: 'مثّل: أستاذ يشرح', categoryId: 'creative' },
  { text: 'مثّل: تفتح هدية مفاجئة', categoryId: 'creative' },
  { text: 'مثّل: لقيت فلوس في الشارع', categoryId: 'creative' },
  { text: 'مثّل: حارس أمن عند البوابة', categoryId: 'creative' },
  { text: 'مثّل: طيار يعلن الهبوط', categoryId: 'creative' },
  { text: 'مثّل: تقنع أمك بشيء', categoryId: 'creative' },
  { text: 'مثّل: بائع فاكهة بالسوق', categoryId: 'creative' },
  { text: 'مثّل: شفت شبح', categoryId: 'creative' },
  { text: 'مثّل: سجّلت هدف بالدقيقة الأخيرة', categoryId: 'creative' },
  { text: 'مثّل: تنتظر بالطابور ساعة', categoryId: 'creative' },
  { text: 'مثّل: طبيب يفحص مريض', categoryId: 'creative' },
  { text: 'مثّل: سائق تاكسي يتذمر', categoryId: 'creative' },
  { text: 'مثّل: مذيع نشرة أخبار', categoryId: 'creative' },
  { text: 'مثّل: تنظر في المرآة بإعجاب', categoryId: 'creative' },
  { text: 'مثّل: طباخ يتذوق طبقه', categoryId: 'creative' },
  { text: 'مثّل: سمعت خبر صادم', categoryId: 'creative' },
  { text: 'مثّل: مدرب يحفز فريقه', categoryId: 'creative' },
  { text: 'مثّل: ممثل يستلم أوسكار', categoryId: 'creative' },
  { text: 'مثّل: تأكل ليمون مباشرة', categoryId: 'creative' },
  { text: 'مثّل: صحيت من نوم عميق', categoryId: 'creative' },
  { text: 'مثّل: عارض أزياء على المنصة', categoryId: 'creative' },
  { text: 'مثّل: مقابلة عمل', categoryId: 'creative' },
  { text: 'مثّل: تطير بالفضاء لأول مرة', categoryId: 'creative' },
  { text: 'مثّل: شخص بعاصفة ريح', categoryId: 'creative' },
  { text: 'مثّل: تحاول تتذكر شيء نسيته', categoryId: 'creative' },
  { text: 'مثّل: لاعب بلياردو', categoryId: 'creative' },
  { text: 'مثّل: تشيل حقيبة ثقيلة جداً', categoryId: 'creative' },
  { text: 'مثّل: تنظر لشيء بعيد جداً', categoryId: 'creative' },
  { text: 'مثّل: راكب دراجة في منحدر', categoryId: 'creative' },
]

export function buildChallengePool(selectedCategories: string[]): SpeedChallenge[] {
  return CHALLENGES.filter((c) => selectedCategories.includes(c.categoryId))
}
